jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Azul JDK 8
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      name: Test in Maven
      run: mvn test
    timeout-minutes: 40
name: Java 8
on:
  repository_dispatch:
    types: trigger-ga___java8.yaml
